// Options pour les filtres articles (liste + formulaire)
// Partagé entre ArticlesListScreen et ArticleEditScreen

export const CODE_FAMILLE_OPTIONS = ['10', '11', '12', '13', '14', '15', '16', '17', '50'];

export const FAMILLE_OPTIONS = [
  { value: 'Accessoires', label: 'Accessoires' },
  { value: 'Audio', label: 'Audio' },
  { value: 'Câble', label: 'Câble' },
  { value: 'Chargeur', label: 'Chargeur' },
  { value: 'Electrique', label: 'Électrique' },
  { value: 'Ergonomie', label: 'Ergonomie' },
  { value: 'Kit', label: 'Kit' },
];

export const TYPE_OPTIONS = [
  { value: 'Souris', label: 'Souris' },
  { value: 'Clavier', label: 'Clavier' },
  { value: 'Dock', label: 'Dock' },
  { value: 'HUB USB', label: 'HUB USB' },
  { value: 'Sécurité', label: 'Sécurité' },
  { value: 'Pointeur laser', label: 'Pointeur laser' },
  { value: 'Dongle', label: 'Dongle' },
  { value: 'Protection', label: 'Protection' },
  { value: 'Clavier / Souris', label: 'Clavier / Souris' },
  { value: 'Casque', label: 'Casque' },
  { value: 'Base de charge', label: 'Base de charge' },
  { value: 'Affichage', label: 'Affichage' },
  { value: 'Rallonge', label: 'Rallonge' },
  { value: 'USB A / USB C', label: 'USB A / USB C' },
  { value: 'USB C / Lightning', label: 'USB C / Lightning' },
  { value: 'USB A / Micro USB', label: 'USB A / Micro USB' },
  { value: 'Réseau', label: 'Réseau' },
  { value: 'USB C', label: 'USB C' },
  { value: 'Alimentation', label: 'Alimentation' },
  { value: 'Multiprise', label: 'Multiprise' },
  { value: "Bras d'écran", label: "Bras d'écran" },
  { value: 'Scanner doc', label: 'Scanner doc' },
  { value: 'Ensemble de matériel', label: 'Ensemble de matériel' },
];

export const SOUS_TYPE_OPTIONS = [
  { value: 'Filaire', label: 'Filaire' },
  { value: 'Sans fil', label: 'Sans fil' },
  { value: 'Agence', label: 'Agence' },
  { value: 'Siège', label: 'Siège' },
  { value: 'D6000', label: 'D6000' },
  { value: '4 ports', label: '4 ports' },
  { value: 'Filtre confidentialité 14"', label: 'Filtre confidentialité 14"' },
  { value: 'Filtre confidentialité 15.6"', label: 'Filtre confidentialité 15.6"' },
  { value: 'Filtre confidentialité 16"', label: 'Filtre confidentialité 16"' },
  { value: 'Filtre confidentialité VIP', label: 'Filtre confidentialité VIP' },
  { value: 'Tablette', label: 'Tablette' },
  { value: 'Pour présentation', label: 'Pour présentation' },
  { value: 'Kit clavier souris', label: 'Kit clavier souris' },
  { value: 'Clavier / Souris', label: 'Clavier / Souris' },
  { value: 'Plantronics', label: 'Plantronics' },
  { value: 'Sacoche', label: 'Sacoche' },
  { value: 'Sac à dos', label: 'Sac à dos' },
  { value: 'Plantronics SF V1', label: 'Plantronics SF V1' },
  { value: 'Plantronics SF V2', label: 'Plantronics SF V2' },
  { value: 'Plantronics filaire', label: 'Plantronics filaire' },
  { value: 'Epsos', label: 'Epsos' },
  { value: 'Poly', label: 'Poly' },
  { value: 'DisplayPort / USB C 1m', label: 'DP / USB C 1m' },
  { value: 'DisplayPort / HDMI 3m', label: 'DP / HDMI 3m' },
  { value: 'HDMI 3 et 2 mètre', label: 'HDMI 3 et 2m' },
  { value: 'HDMI 5 et 10 mètre', label: 'HDMI 5 et 10m' },
  { value: '2m', label: '2 mètres' },
  { value: '3m', label: '3 mètres' },
  { value: 'Générique', label: 'Générique' },
  { value: 'TP', label: 'TP' },
  { value: '65 watt', label: '65 Watt' },
  { value: 'Mini UC', label: 'Mini UC' },
  { value: 'Bras Ergotron', label: 'Bras Ergotron' },
  { value: 'Avec feuille à feuille', label: 'Feuille à feuille' },
  { value: 'Projecteur', label: 'Projecteur' },
  { value: 'Kit audio', label: 'Kit audio' },
  { value: 'Kit complet', label: 'Kit complet' },
];

export const MARQUE_OPTIONS = [
  { value: 'DELL', label: 'DELL' },
  { value: 'Cherry', label: 'Cherry' },
  { value: 'StarTec', label: 'StarTec' },
  { value: '3M', label: '3M' },
  { value: 'Générique', label: 'Générique' },
  { value: 'Plantronics', label: 'Plantronics' },
  { value: 'Aurora', label: 'Aurora' },
  { value: 'Urban Factory', label: 'Urban Factory' },
  { value: 'Epsos', label: 'Epsos' },
  { value: 'Poly', label: 'Poly' },
  { value: 'HP', label: 'HP' },
  { value: 'Ergotron', label: 'Ergotron' },
  { value: 'Fujitsu', label: 'Fujitsu' },
];

export const EMPLACEMENT_OPTIONS = [
  { value: 'Stock 5 - R2E3', label: 'Stock 5 - R2E3' },
  { value: 'Stock 5 - R2E4', label: 'Stock 5 - R2E4' },
  { value: 'Stock 5 - R4E3', label: 'Stock 5 - R4E3' },
  { value: 'Stock 5 - R4E4', label: 'Stock 5 - R4E4' },
  { value: 'Stock 5 - R5E2', label: 'Stock 5 - R5E2' },
  { value: 'Stock 5 - R5E3', label: 'Stock 5 - R5E3' },
  { value: 'Stock 5 - R5E5', label: 'Stock 5 - R5E5' },
  { value: 'Stock 8 - Armoire', label: 'Stock 8 - Armoire' },
  { value: 'Stock 8 - Tiroir', label: 'Stock 8 - Tiroir' },
];
