import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, SafeAreaView, ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { useNavigation } from '@react-navigation/native';
import { useAppSelector } from '@/store';
import { selectEffectiveSiteId } from '@/store/slices/siteSlice';
import anomalyDetectionService, { Anomaly } from '@/services/anomalyDetectionService';

export const AnomaliesScreen: React.FC = () => { const navigation = useNavigation<any>(); const siteId = useAppSelector(selectEffectiveSiteId); const [items, setItems] = useState<Anomaly[]>([]); const [loading, setLoading] = useState(true); const load = useCallback(async () => { setLoading(true); try { setItems(await anomalyDetectionService.detect(siteId ?? undefined)); } catch (error) { Alert.alert('Anomalies', (error as Error).message); } finally { setLoading(false); } }, [siteId]); useEffect(() => { load().catch(() => {}); }, [load]); return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={() => navigation.goBack()} style={styles.back}><Icon name="arrow-left" size={21} color="#17352A" /></Pressable><View><Text style={styles.eyebrow}>QUALITÉ DES DONNÉES</Text><Text style={styles.title}>Anomalies détectées</Text></View><Pressable onPress={() => load()} style={styles.refresh}><Icon name="refresh" size={19} color="#007A55" /></Pressable></View>{loading ? <View style={styles.loader}><ActivityIndicator color="#007A55" /><Text style={styles.muted}>Analyse en cours...</Text></View> : <ScrollView contentContainerStyle={styles.content}>{items.length === 0 ? <Text style={styles.empty}>Aucune anomalie détectée.</Text> : items.map(item => <View key={item.id} style={styles.row}><Icon name={item.severity === 'critical' ? 'alert-octagon' : item.severity === 'warning' ? 'alert-outline' : 'information-outline'} size={22} color={item.severity === 'critical' ? '#C2415A' : item.severity === 'warning' ? '#B45309' : '#2563EB'} /><View style={styles.body}><Text style={styles.titleRow}>{item.title}</Text><Text style={styles.detail}>{item.detail}</Text></View></View>)}</ScrollView>}</SafeAreaView>; };
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F5F5F0' }, header: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 16, backgroundColor: '#FFFFFF' }, back: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#EEF5F0', alignItems: 'center', justifyContent: 'center' }, refresh: { width: 36, height: 36, borderRadius: 10, backgroundColor: '#EAF4EE', alignItems: 'center', justifyContent: 'center' }, eyebrow: { color: '#B45309', fontSize: 10, fontWeight: '800', letterSpacing: 1 }, title: { color: '#17352A', fontSize: 19, fontWeight: '800' }, content: { padding: 14, gap: 8 }, loader: { alignItems: 'center', justifyContent: 'center', padding: 40, gap: 10 }, muted: { color: '#718078' }, row: { flexDirection: 'row', gap: 10, padding: 13, borderRadius: 13, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DCE8DF' }, body: { flex: 1 }, titleRow: { color: '#17352A', fontSize: 13, fontWeight: '800' }, detail: { color: '#617068', fontSize: 11, lineHeight: 16, marginTop: 4 }, empty: { color: '#718078', textAlign: 'center', padding: 30 }, });
export default AnomaliesScreen;
