import React, { useCallback, useEffect, useState } from 'react';
import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { useNavigation } from '@react-navigation/native';
import { getSupabaseClient, tables } from '@/api/supabase';

export const AuditHistoryScreen: React.FC = () => { const navigation = useNavigation<any>(); const [rows, setRows] = useState<any[]>([]); const load = useCallback(async () => { const { data, error } = await getSupabaseClient().from(tables.journalModifications).select('*').order('createdAt', { ascending: false }).limit(100); if (error) throw new Error(error.message); setRows(data ?? []); }, []); useEffect(() => { load().catch(error => Alert.alert('Audit', error.message)); }, [load]); return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={() => navigation.goBack()} style={styles.back}><Icon name="arrow-left" size={21} color="#17352A" /></Pressable><View><Text style={styles.eyebrow}>SÉCURITÉ</Text><Text style={styles.title}>Historique détaillé</Text></View></View><ScrollView contentContainerStyle={styles.content}>{rows.length === 0 ? <Text style={styles.empty}>Aucune modification enregistrée.</Text> : rows.map((row, index) => <View key={String(row.id ?? index)} style={styles.row}><View style={styles.icon}><Icon name="history" size={17} color="#007A55" /></View><View style={styles.body}><Text style={styles.action}>{row.action ?? row.champModifie ?? 'Modification'} · {row.entityType ?? row.table_name ?? 'Article'}</Text><Text style={styles.detail}>{row.oldValue ? `Avant : ${JSON.stringify(row.oldValue)}` : row.ancienneValeur ? `Avant : ${row.ancienneValeur}` : ''}</Text><Text style={styles.detail}>{row.newValue ? `Après : ${JSON.stringify(row.newValue)}` : row.nouvelleValeur ? `Après : ${row.nouvelleValeur}` : ''}</Text><Text style={styles.meta}>{row.createdAt ? new Date(row.createdAt).toLocaleString('fr-FR') : row.date_modification ?? ''} · utilisateur {row.userId ?? row.technicien_id ?? 'inconnu'}</Text></View></View>)}</ScrollView></SafeAreaView>; };
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F5F5F0' }, header: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 16, backgroundColor: '#FFFFFF' }, back: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#EEF5F0', alignItems: 'center', justifyContent: 'center' }, eyebrow: { color: '#007A55', fontSize: 10, fontWeight: '800', letterSpacing: 1 }, title: { color: '#17352A', fontSize: 21, fontWeight: '800' }, content: { padding: 14, gap: 8 }, row: { flexDirection: 'row', gap: 10, padding: 12, borderRadius: 13, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DCE8DF' }, icon: { width: 34, height: 34, borderRadius: 10, backgroundColor: '#EAF4EE', alignItems: 'center', justifyContent: 'center' }, body: { flex: 1 }, action: { color: '#17352A', fontWeight: '800', fontSize: 13 }, detail: { color: '#617068', fontSize: 11, marginTop: 3 }, meta: { color: '#82948A', fontSize: 10, marginTop: 6 }, empty: { color: '#718078', textAlign: 'center', padding: 30 }, });
export default AuditHistoryScreen;
