import React, { useState } from 'react';
import { Alert, SafeAreaView, StyleSheet, Text, View, Pressable } from 'react-native';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { useNavigation } from '@react-navigation/native';
import localBackupService from '@/services/localBackupService';
import remoteBackupService from '@/services/remoteBackupService';
import { useAppSelector } from '@/store';

export const BackupScreen: React.FC = () => { const navigation = useNavigation<any>(); const technicianId = useAppSelector(state => state.auth.currentTechnicien?.id); const [working, setWorking] = useState(false); const run = async (action: () => Promise<void | string>, success: string) => { setWorking(true); try { await action(); Alert.alert('Sauvegarde', success); } catch (error) { if (!(error as any)?.code?.includes?.('DOCUMENT_PICKER_CANCELED')) Alert.alert('Sauvegarde', (error as Error).message); } finally { setWorking(false); } }; return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={() => navigation.goBack()} style={styles.back}><Icon name="arrow-left" size={21} color="#17352A" /></Pressable><View><Text style={styles.eyebrow}>DONNÉES</Text><Text style={styles.title}>Sauvegarde</Text></View></View><View style={styles.content}><Text style={styles.hint}>Sauvegarde locale des préférences et historique, ou snapshot distant des données Supabase.</Text><Pressable disabled={working} onPress={() => run(() => localBackupService.exportBackup(), 'Fichier de sauvegarde prêt à être partagé.')} style={styles.button}><Icon name="content-save-outline" size={20} color="#FFFFFF" /><Text style={styles.buttonText}>Exporter localement</Text></Pressable><Pressable disabled={working} onPress={() => run(() => localBackupService.importBackup(), 'Sauvegarde locale restaurée.')} style={[styles.button, styles.secondary]}><Icon name="backup-restore" size={20} color="#007A55" /><Text style={[styles.buttonText, styles.secondaryText]}>Restaurer localement</Text></Pressable><Pressable disabled={working || technicianId == null} onPress={() => run(() => remoteBackupService.create(String(technicianId)), 'Snapshot distant créé dans Supabase.')} style={styles.button}><Icon name="cloud-upload-outline" size={20} color="#FFFFFF" /><Text style={styles.buttonText}>Créer une sauvegarde distante</Text></Pressable><Pressable disabled={working || technicianId == null} onPress={() => run(() => remoteBackupService.restoreLatest(String(technicianId)), 'Dernière sauvegarde distante restaurée localement.')} style={[styles.button, styles.secondary]}><Icon name="cloud-download-outline" size={20} color="#007A55" /><Text style={[styles.buttonText, styles.secondaryText]}>Restaurer la dernière sauvegarde distante</Text></Pressable></View></SafeAreaView>; };
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F5F5F0' }, header: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 16, backgroundColor: '#FFFFFF' }, back: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#EEF5F0', alignItems: 'center', justifyContent: 'center' }, eyebrow: { color: '#007A55', fontSize: 10, fontWeight: '800', letterSpacing: 1 }, title: { color: '#17352A', fontSize: 21, fontWeight: '800' }, content: { padding: 16, gap: 12 }, hint: { color: '#617068', fontSize: 13, lineHeight: 19 }, button: { minHeight: 52, borderRadius: 13, backgroundColor: '#007A55', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 }, buttonText: { color: '#FFFFFF', fontWeight: '800' }, secondary: { backgroundColor: '#EAF4EE' }, secondaryText: { color: '#007A55' }, });
export default BackupScreen;
