const SCREENS_DATA = {
  install: {
    title: 'Installation',
    icon: '📲',
    steps: [
      {
        num: 1,
        title: 'Ouvrir le Google Play Store',
        desc: "Sur votre telephone Android, ouvrez l'application Google Play Store.",
        screenshot: null,
        screenshotAlt: null,
      },
      {
        num: 2,
        title: 'Telecharger IT-Inventory',
        desc: 'Tapez IT-Inventory dans la barre de recherche et appuyez sur Installer.',
        screenshot: null,
        playLink: 'https://play.google.com/store/apps/details?id=com.itinventory',
      },
      {
        num: 3,
        title: "Lancer l'app pour la premiere fois",
        desc: 'Le loader anime apparait puis les 4 slides onboarding.',
        screenshot: 'assets/screens/01_splash.png',
        screenshotAlt: 'Ecran de chargement IT-Inventory style Credit Agricole',
        screenLabel: 'Splash screen',
      },
      {
        num: 4,
        title: 'Autoriser la camera',
        desc: "Acceptez l'acces camera quand Android vous le demande.",
        screenshot: null,
        tip: "La camera est utilisee uniquement pour scanner des codes-barres.",
      },
    ],
  },
  firstLaunch: {
    title: 'Premier lancement',
    icon: '🚀',
    steps: [
      {
        num: 1,
        title: 'Onboarding (4 slides)',
        desc: 'Glissez les slides de presentation ou appuyez sur PASSER.',
        screenshot: 'assets/screens/02_onboarding_1.png',
        screenshotAlt: 'Slide 1 onboarding IT-Inventory',
        screenLabel: 'Onboarding',
      },
      {
        num: 2,
        title: 'Se connecter',
        desc: 'Entrez vos identifiants fournis par administrateur puis appuyez sur Se connecter.',
        screenshot: 'assets/screens/06_login.png',
        screenshotAlt: 'Ecran de connexion IT-Inventory',
        screenLabel: 'Connexion',
      },
      {
        num: 3,
        title: 'Choisir votre site',
        desc: 'Selectionnez Epinal, Stock 5eme, Stock 8eme ou TCS.',
        screenshot: 'assets/screens/07_site_select.png',
        screenshotAlt: 'Selection du site actif dans IT-Inventory',
        screenLabel: 'Choix du site',
      },
      {
        num: 4,
        title: 'Le Dashboard',
        desc: 'Vous etes pret. Le dashboard affiche stock et actions rapides.',
        screenshot: 'assets/screens/08_dashboard.png',
        screenshotAlt: 'Dashboard IT-Inventory',
        screenLabel: 'Dashboard',
      },
    ],
  },
  articles: {
    title: 'Articles',
    icon: '📦',
    steps: [
      {
        num: 1,
        title: 'Onglet Articles',
        desc: "Appuyez sur l'onglet Articles dans la barre du bas.",
        screenshot: 'assets/screens/09_articles_list.png',
        screenshotAlt: 'Liste des articles dans IT-Inventory',
        screenLabel: 'Liste articles',
      },
      {
        num: 2,
        title: "Detail d'un article",
        desc: 'Tapez sur un article pour voir son detail: stock, historique, etat.',
        screenshot: 'assets/screens/10_article_detail.png',
        screenshotAlt: 'Detail article IT-Inventory',
        screenLabel: 'Detail article',
      },
      {
        num: 3,
        title: 'Declarer un article defectueux',
        desc: 'Choisissez Defectueux puis precisez le nombre avec le stepper.',
        screenshot: 'assets/screens/11_article_condition.png',
        screenshotAlt: 'Section etat article defectueux avec stepper',
        screenLabel: 'Etat article',
        tip: 'Le nombre defectueux ne peut pas depasser le stock total.',
      },
    ],
  },
  parcPC: {
    title: 'Parc PC',
    icon: '💻',
    steps: [
      {
        num: 1,
        title: 'Onglet Parc PC',
        desc: "Appuyez sur l'onglet PC dans la barre du bas.",
        screenshot: 'assets/screens/12_parc_pc.png',
        screenshotAlt: 'Parc PC portables IT-Inventory',
        screenLabel: 'Parc PC',
      },
      {
        num: 2,
        title: 'Declarer un PC en panne',
        desc: 'Choisissez type, priorite et description puis confirmez.',
        screenshot: 'assets/screens/14_pc_panne_modal.png',
        screenshotAlt: 'Modal declaration panne PC type et priorite',
        screenLabel: 'Declarer panne',
        tip: 'La priorite Critique signale le PC en urgence dans le tableau de bord.',
      },
      {
        num: 3,
        title: 'Renommer un PC',
        desc: "Donnez un nom d'affichage, le hostname reste inchange.",
        screenshot: 'assets/screens/15_pc_rename.png',
        screenshotAlt: 'Modal renommage PC IT-Inventory',
        screenLabel: 'Renommer PC',
      },
    ],
  },
  scanner: {
    title: 'Scanner',
    icon: '🔍',
    steps: [
      {
        num: 1,
        title: 'Ouvrir le scanner',
        desc: 'Appuyez sur le bouton central vert QR code dans la barre du bas.',
        screenshot: 'assets/screens/16_scanner.png',
        screenshotAlt: 'Ecran scanner IT-Inventory sur Android',
        screenLabel: 'Scanner',
      },
      {
        num: 2,
        title: 'Pointer vers le code-barres',
        desc: "Maintenez le telephone a 10-20 cm. L'article est reconnu automatiquement.",
        screenshot: 'assets/screens/17_scan_result.png',
        screenshotAlt: 'Resultat scan article identifie',
        screenLabel: 'Resultat scan',
        tip: "Si la reconnaissance est lente, augmentez l'eclairage.",
      },
      {
        num: 3,
        title: "Choisir l'action",
        desc: 'Selectionnez Entree, Sortie ou Consultation.',
        screenshot: 'assets/screens/18_mouvement_flow.png',
        screenshotAlt: 'Saisie mouvement apres scan',
        screenLabel: 'Choisir action',
      },
    ],
  },
  mouvements: {
    title: 'Mouvements',
    icon: '🔄',
    steps: [
      {
        num: 1,
        title: 'Onglet Mouvements',
        desc: "Appuyez sur l'onglet Mouvements.",
        screenshot: 'assets/screens/19_mouvements_list.png',
        screenshotAlt: 'Historique mouvements IT-Inventory',
        screenLabel: 'Mouvements',
      },
      {
        num: 2,
        title: 'Filtrer par periode',
        desc: "Utilisez Aujourd'hui, 7 jours ou 30 jours.",
        screenshot: 'assets/screens/19_mouvements_list.png',
        screenshotAlt: 'Filtres periode mouvements',
        screenLabel: 'Filtre periode',
      },
    ],
  },
  multiSites: {
    title: 'Multi-sites',
    icon: '🏢',
    steps: [
      {
        num: 1,
        title: 'Changer de site',
        desc: 'Touchez la pill verte affichant le site actif sur dashboard.',
        screenshot: 'assets/screens/07_site_select.png',
        screenshotAlt: 'Selecteur site actif IT-Inventory',
        screenLabel: 'Changer site',
      },
      {
        num: 2,
        title: 'Selectionner un site',
        desc: 'Tapez sur le site souhaite. Le site actif affiche un badge ACTIF.',
        screenshot: 'assets/screens/07_site_select.png',
        screenshotAlt: 'Liste des sites avec un site actif',
        screenLabel: 'Site selectionne',
        tip: 'Tous les mouvements seront rattaches au site actif selectionne.',
      },
    ],
  },
};
